name: data_visualization
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  async:
  bloc: ^8.1.3
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  equatable: ^2.0.5
  go_router: ^10.0.0
  intl: ^0.18.0
  get_it: ^7.6.0
  injectable: ^2.1.1
  retrofit: ^4.0.1
  dio: ^5.2.1+1
  rxdart: ^0.27.7
  http: ^1.1.0
  image: ^4.1.3
  decimal: ^2.3.3
  collection:
  sliver_tools: ^0.2.12
  uuid: ^3.0.7
  permission_handler: ^10.4.5
  webview_flutter: ^4.4.4
  csv: ^5.1.1
  freezed_annotation: ^2.4.1
  fl_chart: ^0.66.2
  word_cloud: ^1.0.1
  stream_transform:
  provider:
  flutter_colorpicker: ^1.0.3
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
flutter:
  uses-material-design: true

  assets:
    - assets/data/
